# Generated by Django 4.2.1 on 2023-06-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compressor1', '0003_alter_creategif_gif_image_alter_creategif_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creategif',
            name='gif_image',
            field=models.ImageField(blank=True, max_length=1028, null=True, upload_to='uncreated_images'),
        ),
        migrations.AlterField(
            model_name='creategif',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='uncreated_videos'),
        ),
    ]
