# Generated by Django 4.2.1 on 2023-08-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compressor1', '0004_alter_creategif_gif_image_alter_creategif_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Compressedimage',
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='image',
            field=models.ImageField(max_length=1028, null=True, upload_to='uploads'),
        ),
    ]
