# Generated by Django 4.2.1 on 2023-08-04 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compressor1', '0005_delete_compressedimage_alter_uploadimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creategif',
            name='video',
        ),
    ]
