# Generated by Django 4.2.1 on 2023-08-04 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compressor1', '0006_remove_creategif_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Creategif',
        ),
    ]
