# Generated by Django 3.2.21 on 2024-01-29 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compressor1', '0008_creategif'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Creategif',
        ),
    ]
