# Generated by Django 4.0.6 on 2023-06-15 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_logged_in_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logged_in_user',
            old_name='user',
            new_name='l_user',
        ),
    ]
