# Generated by Django 4.0.6 on 2023-06-15 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_user_logged_in_user_l_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logged_in_user',
            old_name='l_user',
            new_name='user',
        ),
    ]
