# Generated by Django 4.2.1 on 2023-07-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_termsandcondition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsandcondition',
            name='termsandcondition',
            field=models.BooleanField(default=False),
        ),
    ]
