# Generated by Django 4.2.1 on 2023-07-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_termsandcondition_termsandcondition'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='termsandcondition',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TermsandCondition',
        ),
    ]
