# Generated by Django 4.2.1 on 2023-07-05 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_termsandcondition_delete_termsandcondition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='termsandcondition',
            field=models.BooleanField(default=False),
        ),
    ]
