# Generated by Django 4.2.1 on 2023-07-31 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0012_remove_profile_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification_status',
            name='otp_expiration_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='verification_status',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
