# Generated by Django 4.2.1 on 2023-07-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_verification_status_otp_expiration_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification_status',
            name='otp_expiration_time',
            field=models.DateTimeField(null=True),
        ),
    ]
