# Generated by Django 4.2.1 on 2023-07-31 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_verification_status_otp_expiration_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verification_status',
            name='otp_expiration_time',
        ),
    ]
